<?php
// $Id: i18n_field.install jareyero Exp $

/**
 * @file
 * Install, update and uninstall functions for the i18n_field module.
 */

/**
 * Implements hook_install()
 */
function i18n_field_install() {
  // If updating from D6, module changed name
  if (variable_get('i18n_drupal6_update')) {
    i18n_field_update_7000();
  }  
}

/**
 * Implements hook_i18n_drupal6_update
 * 
 * Update old string names
 */
function i18n_field_update_7000() {
  // @todo
}
