<?php
// $Id: i18n_block.module,v 1.7.2.25 2010/08/12 02:06:20 mirodietiker Exp $

/**
 * @file
 * Internationalization (i18n) submodule: Multilingual meta-blocks
 *
 * @author Jose A. Reyero, 2005
 *
 * @ TODO Add strings on block update.
 */

// Tag for localizable block, cannot be any language.
define('I18N_BLOCK_LOCALIZE', '__LOCALIZE__');
// Block type: localizable
define('I18N_BLOCK_LOCALIZABLE', 1);
// Block type: block with language
define('I18N_BLOCK_LANGUAGE', 0);

/**
 * Implements hook_block_list_alter().
 *
 * Translate localizable blocks.
 * 
 * To be run after all block visibility modules have run, just translate the blocks to be displayed
 */
function i18n_block_block_list_alter(&$blocks) {
  global $theme_key, $language;

  // Build an array of node types for each block.
  $block_languages = array();
  $result = db_query('SELECT module, delta, language FROM {i18n_block_language}');
  foreach ($result as $record) {
    $block_languages[$record->module][$record->delta][$record->language] = TRUE;
  }

  foreach ($blocks as $key => $block) {
    if (!isset($block->theme) || !isset($block->status) || $block->theme != $theme_key || $block->status != 1) {
      // This block was added by a contrib module, leave it in the list.
      continue;
    }
    if (isset($block_languages[$block->module][$block->delta]) && !isset($block_languages[$block->module][$block->delta][$language->language])) {
      // Block not visible for this language
      unset($blocks[$key]);
    }
  }
}

/**
 * Implements hook_block_view()
 */
function i18n_block_block_view_alter(&$data, $block) {
  if (!empty($block->i18n_mode)) {
    if ($block->title && $block->title != '<none>') {
      $block->title = i18nstrings_translate(array('blocks', $block->module, $block->delta, 'title'), $block->title);
    }
    if ($block->module == 'block' && isset($data['content'])) {
      $data['content'] = i18nstrings_translate(array('blocks', $block->module, $block->delta, 'body'), $data['content']);
    } 
  }  
}

/**
 * Implements hook_help().
 */
function i18n_block_help($path, $arg) {
  switch ($path) {
    case 'admin/help#i18n_block':
      $output = '<p>' . t('This module provides support for multilingual blocks.') . '</p>';
      $output .= '<p>' . t('You can set up a language for a block or define it as translatable:') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('Blocks with a language will be displayed only in pages with that language.') . '</li>';
      $output .= '<li>' . t('Translatable blocks can be translated using the localization interface.') . '</li>';
      $output .= '</ul>';
      $output .= '<p>' . t('To search and translate strings, use the <a href="@translate-interface">translation interface</a> pages.', array('@translate-interface' => url('admin/build/translate'))) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_query_alter().
 */
/*
function i18n_block_query_alter(QueryAlterableInterface $query) {
  $current = i18n_get_lang();
  if ($query->hasTag('block_load')) {
    $query->leftJoin('i18n_blocks', 'i18n', 'b.module = i18n.module AND b.delta = i18n.delta');
    $query->condition(i18n_db_rewrite_where('i18n', 'block', 'simple'));
  }
}
*/

/**
 * Implements hook_locale().
 *
 * This one doesn't need locale refresh because strings are stored from module
 * config form.
 */
function i18n_block_locale($op = 'groups', $group = NULL) {
  switch ($op) {
    case 'groups':
      return array('blocks' => t('Blocks'));
    case 'info':
      $info['blocks']['refresh callback'] = 'i18n_block_locale_refresh';
      $info['blocks']['format'] = TRUE;
      return $info;
  }
}

/**
 * Refresh all strings.
 */
function i18n_block_locale_refresh() {
  $query = db_select('block', 'b')
    ->distinct()
    ->fields('b', array('module', 'delta', 'title', 'i18n_mode'))
    ->fields('bc', array('body', 'format'))
    ->condition('i18n_mode', 1);
  $query->leftJoin('block_custom', 'bc', 'b.bid = bc.bid');
  $result = $query->execute()
    ->fetchAll(PDO::FETCH_OBJ);
  foreach ($result as $block) {
    // If the block has a custom title and no language it must be translated
    if ($block->title && $block->title != '<none>') {
      i18nstrings_update("blocks:$block->module:$block->delta:title", $block->title);
    }
    // If the block has body and no language, must be a custom block (box)
    if ($block->body) {
      i18nstrings_update("blocks:$block->module:$block->delta:body", $block->body, array('format' => $block->format));
    }
  }
  return TRUE; // Meaning it completed with no issues
}

/**
 * Remove strings for deleted custom blocks.
 */
function i18n_block_block_delete_submit(&$form, $form_state) {
  $delta = $form_state['values']['delta'];
  // Delete stored strings for the title and content fields.
  i18nstrings_remove_string("blocks:block:$delta:title");
  i18nstrings_remove_string("blocks:block:$delta:body");
}

/**
 * Implements block hook_form_FORM_ID_alter().
 *
 * Remove block title for multilingual blocks.
 */
function i18n_block_form_block_add_block_form_alter(&$form, &$form_state, $form_id) {
  //i18n_block_alter_forms($form, $form_state, $form_id);
 i18n_block_form_block_admin_configure_alter($form, $form_state, $form_id);
}

/**
 * Implements block hook_form_FORM_ID_alter().
 *
 * Remove block title for multilingual blocks.
 */
function i18n_block_form_block_admin_configure_alter(&$form, &$form_state, $form_id) {
  $default_options = db_query("SELECT language FROM {i18n_block_language} WHERE module = :module AND delta = :delta", array(
    ':module' => $form['module']['#value'],
    ':delta' => $form['delta']['#value'],
  ))->fetchCol();
  $form['i18n_block']['languages'] = array(
    '#type' => 'fieldset',
    '#title' => t('Languages'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'visibility',
    '#weight' => 5,
  );
  $form['i18n_block']['languages']['languages'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Show block for specific languages'),
    '#default_value' => $default_options,
    '#options' => locale_language_list('name', TRUE),
    '#description' => t('Show this block only on pages for the given language(s). If you select no language, there will be no language-specific limitation.'),
  );
  // Add translatable option, just title for module blocks, title and content for custom blocks.
  $block = block_load($form['module']['#value'], $form['delta']['#value']);
  $form['i18n_block']['languages']['i18n_mode'] = array(
    '#type' => 'radios',
    '#title' => t('Block translation'),
    '#default_value' => $block->i18n_mode,
    '#options' => array(t('Disabled'), t('Enabled')),
    '#description' => $form['module']['#value'] == 'block' ? t('Make this block title and content translatable.') : t('Make this block title translatable.'),
  );
  $form['#submit'][] = 'i18n_block_form_block_admin_configure_submit';  
}

/**
 * Form submit handler for block configuration form.
 *
 * @see i18n_block_form_block_admin_configure_alter()
 */
function i18n_block_form_block_admin_configure_submit(&$form, &$form_state) {
  $module = $form_state['values']['module'];
  $delta = $form_state['values']['delta'];

  // Update block languages
  db_delete('i18n_block_language')
    ->condition('module', $module)
    ->condition('delta', $delta)
    ->execute();
  $query = db_insert('i18n_block_language')->fields(array('language', 'module', 'delta'));
  foreach (array_filter($form_state['values']['languages']) as $language) {
    $query->values(array(
      'language' => $language,
      'module' => $module,
      'delta' => $delta,
    ));
  }
  $query->execute();
  // Update block translation options and strings
  if (isset($form_state['values']['i18n_mode'])) {
    db_update('block')
      ->fields(array('i18n_mode' => $form_state['values']['i18n_mode']))
      ->condition('module', $module)
      ->condition('delta', $delta)
      ->execute();
    i18n_block_update_strings($form_state['values'], $form_state['values']['i18n_mode']);
  }
}

/**
 * Update block strings
 */
function i18n_block_update_strings($block, $i18n_mode = TRUE) {
  $title = $i18n_mode && $block['title'] !== '<none>' ? $block['title'] : '';
  i18nstrings_update(array('blocks', $block['module'], $block['delta'], 'title'), $title);
  if (isset($block['body'])) {
    if ($i18n_mode) {
      i18nstrings_update(array('blocks', $block['module'], $block['delta'], 'body'), $block['body']['value'], array('format' => $block['body']['format']));
    } 
    else {
      i18nstrings_remove(array('blocks', $block['module'], $block['delta'], 'body'));
    }
  }
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * Adds node specific submit handler to delete custom block form.
 *
 * @see block_custom_block_delete()
 */
function i18n_block_form_block_custom_block_delete_alter(&$form, &$form_state) {
  $form['#submit'][] = 'i18n_block_form_block_custom_block_delete_submit';
}

/**
 * Form submit handler for custom block delete form.
 *
 * @see node_form_block_custom_block_delete_alter()
 */
function i18n_block_form_block_custom_block_delete_submit($form, &$form_state) {
  db_delete('i18n_block_language')
    ->condition('module', 'block')
    ->condition('delta', $form_state['values']['bid'])
    ->execute();
}

/**
 * Translate block.
 *
 * @param $block
 *   Core block object
 */
function i18n_block_translate_block($block) {
  if (!empty($block->content) && $localizable) {
    $block->content = i18nstrings_text("blocks:$block->module:$block->delta:body", $block->content);
  }
  // If it has a custom title, localize it
  if (!empty($block->title) && $block->title != '<none>') {
    // Check plain here to allow module generated titles to keep any markup.
    $block->subject = i18nstrings_string("blocks:$block->module:$block->delta:title", $block->subject);
  }
  return $block;
}
